/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VeronicaCurriculoCertoRouteImport } from './routes/veronica-curriculo-certo'
import { Route as VideoIaRouteImport } from './routes/video-ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeronicaCurriculoCertoRoute = VeronicaCurriculoCertoRouteImport.update({
  id: '/veronica-curriculo-certo',
  path: '/veronica-curriculo-certo',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIaRoute = VideoIaRouteImport.update({
  id: '/video-ia',
  path: '/video-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/veronica-curriculo-certo': typeof VeronicaCurriculoCertoRoute
  '/video-ia': typeof VideoIaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/veronica-curriculo-certo': typeof VeronicaCurriculoCertoRoute
  '/video-ia': typeof VideoIaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/veronica-curriculo-certo': typeof VeronicaCurriculoCertoRoute
  '/video-ia': typeof VideoIaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/veronica-curriculo-certo' | '/video-ia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/veronica-curriculo-certo' | '/video-ia'
  id: '__root__' | '/' | '/veronica-curriculo-certo' | '/video-ia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VeronicaCurriculoCertoRoute: typeof VeronicaCurriculoCertoRoute
  VideoIaRoute: typeof VideoIaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veronica-curriculo-certo': {
      id: '/veronica-curriculo-certo'
      path: '/veronica-curriculo-certo'
      fullPath: '/veronica-curriculo-certo'
      preLoaderRoute: typeof VeronicaCurriculoCertoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-ia': {
      id: '/video-ia'
      path: '/video-ia'
      fullPath: '/video-ia'
      preLoaderRoute: typeof VideoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VeronicaCurriculoCertoRoute: VeronicaCurriculoCertoRoute,
  VideoIaRoute: VideoIaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
