/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as AulaZeroRouteImport } from './routes/aula-zero'
import { Route as ComandosRouteImport } from './routes/comandos'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PromptPacksRouteImport } from './routes/prompt-packs'
import { Route as SeloDemoRouteImport } from './routes/selo-demo'
import { Route as SelosRouteImport } from './routes/selos'
import { Route as VeronicaAnalyticsRouteImport } from './routes/veronica-analytics'
import { Route as VeronicaCurriculoCertoRouteImport } from './routes/veronica-curriculo-certo'
import { Route as VeronicaCurriculoCertoRhRouteImport } from './routes/veronica-curriculo-certo-rh'
import { Route as VeronicaNauticaRouteImport } from './routes/veronica-nautica'
import { Route as VeronicaRedeRouteImport } from './routes/veronica-rede'
import { Route as VeronicaSecurityRouteImport } from './routes/veronica-security'
import { Route as VideoIaRouteImport } from './routes/video-ia'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminArtigosRouteImport } from './routes/admin/artigos'
import { Route as AdminImagensRouteImport } from './routes/admin/imagens'
import { Route as AdminVeronicaUniverseRouteImport } from './routes/admin/veronica-universe'
import { Route as AdminWireRouteImport } from './routes/admin/wire'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogExpedienteRouteImport } from './routes/blog/expediente'
import { Route as BlogRedeDeFontesRouteImport } from './routes/blog/rede-de-fontes'
import { Route as ClientesIndexRouteImport } from './routes/clientes/index'
import { Route as PreviewExpressOperationsBRouteImport } from './routes/preview/express-operations-b'
import { Route as PropostaExpressEntulhoRouteImport } from './routes/proposta/express-entulho'
import { Route as SeloSerialRouteImport } from './routes/selo/$serial'
import { Route as BlogEditoriaBeatRouteImport } from './routes/blog/editoria/$beat'
import { Route as BlogRedeDeFontesRelatoriosRouteImport } from './routes/blog/rede-de-fontes/relatorios'
import { Route as ClientesExpressEntulhoOperacoesRouteImport } from './routes/clientes/express-entulho/operacoes'
import { Route as ClientesExpressEntulhoOperacoesDemoRouteImport } from './routes/clientes/express-entulho/operacoes-demo'
import { Route as ClientesExpressEntulhoPropostaRouteImport } from './routes/clientes/express-entulho/proposta'
import { Route as PreviewExpressOperationsBSplatRouteImport } from './routes/preview/express-operations-b/$'
import { Route as ClientesExpressEntulhoOperacoesIndexRouteImport } from './routes/clientes/express-entulho/operacoes/index'
import { Route as ClientesExpressEntulhoOperacoesSecaoRouteImport } from './routes/clientes/express-entulho/operacoes/$secao'
import { Route as ClientesExpressEntulhoOperacoesAprovacoesRouteImport } from './routes/clientes/express-entulho/operacoes/aprovacoes'
import { Route as ClientesExpressEntulhoOperacoesAtendimentoRouteImport } from './routes/clientes/express-entulho/operacoes/atendimento'
import { Route as ClientesExpressEntulhoOperacoesCacambasRouteImport } from './routes/clientes/express-entulho/operacoes/cacambas'
import { Route as ClientesExpressEntulhoOperacoesOperacoesHojeRouteImport } from './routes/clientes/express-entulho/operacoes/operacoes-hoje'
import { Route as ClientesExpressEntulhoOperacoesRegrasDoAgenteRouteImport } from './routes/clientes/express-entulho/operacoes/regras-do-agente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaZeroRoute = AulaZeroRouteImport.update({
  id: '/aula-zero',
  path: '/aula-zero',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandosRoute = ComandosRouteImport.update({
  id: '/comandos',
  path: '/comandos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptPacksRoute = PromptPacksRouteImport.update({
  id: '/prompt-packs',
  path: '/prompt-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const SeloDemoRoute = SeloDemoRouteImport.update({
  id: '/selo-demo',
  path: '/selo-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SelosRoute = SelosRouteImport.update({
  id: '/selos',
  path: '/selos',
  getParentRoute: () => rootRouteImport,
} as any)
const VeronicaAnalyticsRoute = VeronicaAnalyticsRouteImport.update({
  id: '/veronica-analytics',
  path: '/veronica-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const VeronicaCurriculoCertoRoute = VeronicaCurriculoCertoRouteImport.update({
  id: '/veronica-curriculo-certo',
  path: '/veronica-curriculo-certo',
  getParentRoute: () => rootRouteImport,
} as any)
const VeronicaCurriculoCertoRhRoute =
  VeronicaCurriculoCertoRhRouteImport.update({
    id: '/veronica-curriculo-certo-rh',
    path: '/veronica-curriculo-certo-rh',
    getParentRoute: () => rootRouteImport,
  } as any)
const VeronicaNauticaRoute = VeronicaNauticaRouteImport.update({
  id: '/veronica-nautica',
  path: '/veronica-nautica',
  getParentRoute: () => rootRouteImport,
} as any)
const VeronicaRedeRoute = VeronicaRedeRouteImport.update({
  id: '/veronica-rede',
  path: '/veronica-rede',
  getParentRoute: () => rootRouteImport,
} as any)
const VeronicaSecurityRoute = VeronicaSecurityRouteImport.update({
  id: '/veronica-security',
  path: '/veronica-security',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIaRoute = VideoIaRouteImport.update({
  id: '/video-ia',
  path: '/video-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArtigosRoute = AdminArtigosRouteImport.update({
  id: '/admin/artigos',
  path: '/admin/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImagensRoute = AdminImagensRouteImport.update({
  id: '/admin/imagens',
  path: '/admin/imagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVeronicaUniverseRoute = AdminVeronicaUniverseRouteImport.update({
  id: '/admin/veronica-universe',
  path: '/admin/veronica-universe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWireRoute = AdminWireRouteImport.update({
  id: '/admin/wire',
  path: '/admin/wire',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogExpedienteRoute = BlogExpedienteRouteImport.update({
  id: '/blog/expediente',
  path: '/blog/expediente',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRedeDeFontesRoute = BlogRedeDeFontesRouteImport.update({
  id: '/blog/rede-de-fontes',
  path: '/blog/rede-de-fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewExpressOperationsBRoute =
  PreviewExpressOperationsBRouteImport.update({
    id: '/preview/express-operations-b',
    path: '/preview/express-operations-b',
    getParentRoute: () => rootRouteImport,
  } as any)
const PropostaExpressEntulhoRoute = PropostaExpressEntulhoRouteImport.update({
  id: '/proposta/express-entulho',
  path: '/proposta/express-entulho',
  getParentRoute: () => rootRouteImport,
} as any)
const SeloSerialRoute = SeloSerialRouteImport.update({
  id: '/selo/$serial',
  path: '/selo/$serial',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEditoriaBeatRoute = BlogEditoriaBeatRouteImport.update({
  id: '/blog/editoria/$beat',
  path: '/blog/editoria/$beat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRedeDeFontesRelatoriosRoute =
  BlogRedeDeFontesRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => BlogRedeDeFontesRoute,
  } as any)
const ClientesExpressEntulhoOperacoesRoute =
  ClientesExpressEntulhoOperacoesRouteImport.update({
    id: '/clientes/express-entulho/operacoes',
    path: '/clientes/express-entulho/operacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientesExpressEntulhoOperacoesDemoRoute =
  ClientesExpressEntulhoOperacoesDemoRouteImport.update({
    id: '/clientes/express-entulho/operacoes-demo',
    path: '/clientes/express-entulho/operacoes-demo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientesExpressEntulhoPropostaRoute =
  ClientesExpressEntulhoPropostaRouteImport.update({
    id: '/clientes/express-entulho/proposta',
    path: '/clientes/express-entulho/proposta',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreviewExpressOperationsBSplatRoute =
  PreviewExpressOperationsBSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => PreviewExpressOperationsBRoute,
  } as any)
const ClientesExpressEntulhoOperacoesIndexRoute =
  ClientesExpressEntulhoOperacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClientesExpressEntulhoOperacoesRoute,
  } as any)
const ClientesExpressEntulhoOperacoesSecaoRoute =
  ClientesExpressEntulhoOperacoesSecaoRouteImport.update({
    id: '/$secao',
    path: '/$secao',
    getParentRoute: () => ClientesExpressEntulhoOperacoesRoute,
  } as any)
const ClientesExpressEntulhoOperacoesAprovacoesRoute =
  ClientesExpressEntulhoOperacoesAprovacoesRouteImport.update({
    id: '/aprovacoes',
    path: '/aprovacoes',
    getParentRoute: () => ClientesExpressEntulhoOperacoesRoute,
  } as any)
const ClientesExpressEntulhoOperacoesAtendimentoRoute =
  ClientesExpressEntulhoOperacoesAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => ClientesExpressEntulhoOperacoesRoute,
  } as any)
const ClientesExpressEntulhoOperacoesCacambasRoute =
  ClientesExpressEntulhoOperacoesCacambasRouteImport.update({
    id: '/cacambas',
    path: '/cacambas',
    getParentRoute: () => ClientesExpressEntulhoOperacoesRoute,
  } as any)
const ClientesExpressEntulhoOperacoesOperacoesHojeRoute =
  ClientesExpressEntulhoOperacoesOperacoesHojeRouteImport.update({
    id: '/operacoes-hoje',
    path: '/operacoes-hoje',
    getParentRoute: () => ClientesExpressEntulhoOperacoesRoute,
  } as any)
const ClientesExpressEntulhoOperacoesRegrasDoAgenteRoute =
  ClientesExpressEntulhoOperacoesRegrasDoAgenteRouteImport.update({
    id: '/regras-do-agente',
    path: '/regras-do-agente',
    getParentRoute: () => ClientesExpressEntulhoOperacoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/aula-zero': typeof AulaZeroRoute
  '/comandos': typeof ComandosRoute
  '/portfolio': typeof PortfolioRoute
  '/prompt-packs': typeof PromptPacksRoute
  '/selo-demo': typeof SeloDemoRoute
  '/selos': typeof SelosRoute
  '/veronica-analytics': typeof VeronicaAnalyticsRoute
  '/veronica-curriculo-certo': typeof VeronicaCurriculoCertoRoute
  '/veronica-curriculo-certo-rh': typeof VeronicaCurriculoCertoRhRoute
  '/veronica-nautica': typeof VeronicaNauticaRoute
  '/veronica-rede': typeof VeronicaRedeRoute
  '/veronica-security': typeof VeronicaSecurityRoute
  '/video-ia': typeof VideoIaRoute
  '/admin/artigos': typeof AdminArtigosRoute
  '/admin/imagens': typeof AdminImagensRoute
  '/admin/veronica-universe': typeof AdminVeronicaUniverseRoute
  '/admin/wire': typeof AdminWireRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/expediente': typeof BlogExpedienteRoute
  '/blog/rede-de-fontes': typeof BlogRedeDeFontesRouteWithChildren
  '/preview/express-operations-b': typeof PreviewExpressOperationsBRouteWithChildren
  '/proposta/express-entulho': typeof PropostaExpressEntulhoRoute
  '/selo/$serial': typeof SeloSerialRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/blog/editoria/$beat': typeof BlogEditoriaBeatRoute
  '/blog/rede-de-fontes/relatorios': typeof BlogRedeDeFontesRelatoriosRoute
  '/clientes/express-entulho/operacoes': typeof ClientesExpressEntulhoOperacoesRouteWithChildren
  '/clientes/express-entulho/operacoes-demo': typeof ClientesExpressEntulhoOperacoesDemoRoute
  '/clientes/express-entulho/proposta': typeof ClientesExpressEntulhoPropostaRoute
  '/preview/express-operations-b/$': typeof PreviewExpressOperationsBSplatRoute
  '/clientes/express-entulho/operacoes/$secao': typeof ClientesExpressEntulhoOperacoesSecaoRoute
  '/clientes/express-entulho/operacoes/aprovacoes': typeof ClientesExpressEntulhoOperacoesAprovacoesRoute
  '/clientes/express-entulho/operacoes/atendimento': typeof ClientesExpressEntulhoOperacoesAtendimentoRoute
  '/clientes/express-entulho/operacoes/cacambas': typeof ClientesExpressEntulhoOperacoesCacambasRoute
  '/clientes/express-entulho/operacoes/operacoes-hoje': typeof ClientesExpressEntulhoOperacoesOperacoesHojeRoute
  '/clientes/express-entulho/operacoes/regras-do-agente': typeof ClientesExpressEntulhoOperacoesRegrasDoAgenteRoute
  '/clientes/express-entulho/operacoes/': typeof ClientesExpressEntulhoOperacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/aula-zero': typeof AulaZeroRoute
  '/comandos': typeof ComandosRoute
  '/portfolio': typeof PortfolioRoute
  '/prompt-packs': typeof PromptPacksRoute
  '/selo-demo': typeof SeloDemoRoute
  '/selos': typeof SelosRoute
  '/veronica-analytics': typeof VeronicaAnalyticsRoute
  '/veronica-curriculo-certo': typeof VeronicaCurriculoCertoRoute
  '/veronica-curriculo-certo-rh': typeof VeronicaCurriculoCertoRhRoute
  '/veronica-nautica': typeof VeronicaNauticaRoute
  '/veronica-rede': typeof VeronicaRedeRoute
  '/veronica-security': typeof VeronicaSecurityRoute
  '/video-ia': typeof VideoIaRoute
  '/admin/artigos': typeof AdminArtigosRoute
  '/admin/imagens': typeof AdminImagensRoute
  '/admin/veronica-universe': typeof AdminVeronicaUniverseRoute
  '/admin/wire': typeof AdminWireRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/expediente': typeof BlogExpedienteRoute
  '/blog/rede-de-fontes': typeof BlogRedeDeFontesRouteWithChildren
  '/preview/express-operations-b': typeof PreviewExpressOperationsBRouteWithChildren
  '/proposta/express-entulho': typeof PropostaExpressEntulhoRoute
  '/selo/$serial': typeof SeloSerialRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/blog/editoria/$beat': typeof BlogEditoriaBeatRoute
  '/blog/rede-de-fontes/relatorios': typeof BlogRedeDeFontesRelatoriosRoute
  '/clientes/express-entulho/operacoes-demo': typeof ClientesExpressEntulhoOperacoesDemoRoute
  '/clientes/express-entulho/proposta': typeof ClientesExpressEntulhoPropostaRoute
  '/preview/express-operations-b/$': typeof PreviewExpressOperationsBSplatRoute
  '/clientes/express-entulho/operacoes/$secao': typeof ClientesExpressEntulhoOperacoesSecaoRoute
  '/clientes/express-entulho/operacoes/aprovacoes': typeof ClientesExpressEntulhoOperacoesAprovacoesRoute
  '/clientes/express-entulho/operacoes/atendimento': typeof ClientesExpressEntulhoOperacoesAtendimentoRoute
  '/clientes/express-entulho/operacoes/cacambas': typeof ClientesExpressEntulhoOperacoesCacambasRoute
  '/clientes/express-entulho/operacoes/operacoes-hoje': typeof ClientesExpressEntulhoOperacoesOperacoesHojeRoute
  '/clientes/express-entulho/operacoes/regras-do-agente': typeof ClientesExpressEntulhoOperacoesRegrasDoAgenteRoute
  '/clientes/express-entulho/operacoes': typeof ClientesExpressEntulhoOperacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/aula-zero': typeof AulaZeroRoute
  '/comandos': typeof ComandosRoute
  '/portfolio': typeof PortfolioRoute
  '/prompt-packs': typeof PromptPacksRoute
  '/selo-demo': typeof SeloDemoRoute
  '/selos': typeof SelosRoute
  '/veronica-analytics': typeof VeronicaAnalyticsRoute
  '/veronica-curriculo-certo': typeof VeronicaCurriculoCertoRoute
  '/veronica-curriculo-certo-rh': typeof VeronicaCurriculoCertoRhRoute
  '/veronica-nautica': typeof VeronicaNauticaRoute
  '/veronica-rede': typeof VeronicaRedeRoute
  '/veronica-security': typeof VeronicaSecurityRoute
  '/video-ia': typeof VideoIaRoute
  '/admin/artigos': typeof AdminArtigosRoute
  '/admin/imagens': typeof AdminImagensRoute
  '/admin/veronica-universe': typeof AdminVeronicaUniverseRoute
  '/admin/wire': typeof AdminWireRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/expediente': typeof BlogExpedienteRoute
  '/blog/rede-de-fontes': typeof BlogRedeDeFontesRouteWithChildren
  '/preview/express-operations-b': typeof PreviewExpressOperationsBRouteWithChildren
  '/proposta/express-entulho': typeof PropostaExpressEntulhoRoute
  '/selo/$serial': typeof SeloSerialRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/blog/editoria/$beat': typeof BlogEditoriaBeatRoute
  '/blog/rede-de-fontes/relatorios': typeof BlogRedeDeFontesRelatoriosRoute
  '/clientes/express-entulho/operacoes': typeof ClientesExpressEntulhoOperacoesRouteWithChildren
  '/clientes/express-entulho/operacoes-demo': typeof ClientesExpressEntulhoOperacoesDemoRoute
  '/clientes/express-entulho/proposta': typeof ClientesExpressEntulhoPropostaRoute
  '/preview/express-operations-b/$': typeof PreviewExpressOperationsBSplatRoute
  '/clientes/express-entulho/operacoes/$secao': typeof ClientesExpressEntulhoOperacoesSecaoRoute
  '/clientes/express-entulho/operacoes/aprovacoes': typeof ClientesExpressEntulhoOperacoesAprovacoesRoute
  '/clientes/express-entulho/operacoes/atendimento': typeof ClientesExpressEntulhoOperacoesAtendimentoRoute
  '/clientes/express-entulho/operacoes/cacambas': typeof ClientesExpressEntulhoOperacoesCacambasRoute
  '/clientes/express-entulho/operacoes/operacoes-hoje': typeof ClientesExpressEntulhoOperacoesOperacoesHojeRoute
  '/clientes/express-entulho/operacoes/regras-do-agente': typeof ClientesExpressEntulhoOperacoesRegrasDoAgenteRoute
  '/clientes/express-entulho/operacoes/': typeof ClientesExpressEntulhoOperacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/aula-zero'
    | '/comandos'
    | '/portfolio'
    | '/prompt-packs'
    | '/selo-demo'
    | '/selos'
    | '/veronica-analytics'
    | '/veronica-curriculo-certo'
    | '/veronica-curriculo-certo-rh'
    | '/veronica-nautica'
    | '/veronica-rede'
    | '/veronica-security'
    | '/video-ia'
    | '/admin/artigos'
    | '/admin/imagens'
    | '/admin/veronica-universe'
    | '/admin/wire'
    | '/blog/$slug'
    | '/blog/expediente'
    | '/blog/rede-de-fontes'
    | '/preview/express-operations-b'
    | '/proposta/express-entulho'
    | '/selo/$serial'
    | '/admin/'
    | '/blog/'
    | '/clientes/'
    | '/blog/editoria/$beat'
    | '/blog/rede-de-fontes/relatorios'
    | '/clientes/express-entulho/operacoes'
    | '/clientes/express-entulho/operacoes-demo'
    | '/clientes/express-entulho/proposta'
    | '/preview/express-operations-b/$'
    | '/clientes/express-entulho/operacoes/$secao'
    | '/clientes/express-entulho/operacoes/aprovacoes'
    | '/clientes/express-entulho/operacoes/atendimento'
    | '/clientes/express-entulho/operacoes/cacambas'
    | '/clientes/express-entulho/operacoes/operacoes-hoje'
    | '/clientes/express-entulho/operacoes/regras-do-agente'
    | '/clientes/express-entulho/operacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/aula-zero'
    | '/comandos'
    | '/portfolio'
    | '/prompt-packs'
    | '/selo-demo'
    | '/selos'
    | '/veronica-analytics'
    | '/veronica-curriculo-certo'
    | '/veronica-curriculo-certo-rh'
    | '/veronica-nautica'
    | '/veronica-rede'
    | '/veronica-security'
    | '/video-ia'
    | '/admin/artigos'
    | '/admin/imagens'
    | '/admin/veronica-universe'
    | '/admin/wire'
    | '/blog/$slug'
    | '/blog/expediente'
    | '/blog/rede-de-fontes'
    | '/preview/express-operations-b'
    | '/proposta/express-entulho'
    | '/selo/$serial'
    | '/admin'
    | '/blog'
    | '/clientes'
    | '/blog/editoria/$beat'
    | '/blog/rede-de-fontes/relatorios'
    | '/clientes/express-entulho/operacoes-demo'
    | '/clientes/express-entulho/proposta'
    | '/preview/express-operations-b/$'
    | '/clientes/express-entulho/operacoes/$secao'
    | '/clientes/express-entulho/operacoes/aprovacoes'
    | '/clientes/express-entulho/operacoes/atendimento'
    | '/clientes/express-entulho/operacoes/cacambas'
    | '/clientes/express-entulho/operacoes/operacoes-hoje'
    | '/clientes/express-entulho/operacoes/regras-do-agente'
    | '/clientes/express-entulho/operacoes'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/aula-zero'
    | '/comandos'
    | '/portfolio'
    | '/prompt-packs'
    | '/selo-demo'
    | '/selos'
    | '/veronica-analytics'
    | '/veronica-curriculo-certo'
    | '/veronica-curriculo-certo-rh'
    | '/veronica-nautica'
    | '/veronica-rede'
    | '/veronica-security'
    | '/video-ia'
    | '/admin/artigos'
    | '/admin/imagens'
    | '/admin/veronica-universe'
    | '/admin/wire'
    | '/blog/$slug'
    | '/blog/expediente'
    | '/blog/rede-de-fontes'
    | '/preview/express-operations-b'
    | '/proposta/express-entulho'
    | '/selo/$serial'
    | '/admin/'
    | '/blog/'
    | '/clientes/'
    | '/blog/editoria/$beat'
    | '/blog/rede-de-fontes/relatorios'
    | '/clientes/express-entulho/operacoes'
    | '/clientes/express-entulho/operacoes-demo'
    | '/clientes/express-entulho/proposta'
    | '/preview/express-operations-b/$'
    | '/clientes/express-entulho/operacoes/$secao'
    | '/clientes/express-entulho/operacoes/aprovacoes'
    | '/clientes/express-entulho/operacoes/atendimento'
    | '/clientes/express-entulho/operacoes/cacambas'
    | '/clientes/express-entulho/operacoes/operacoes-hoje'
    | '/clientes/express-entulho/operacoes/regras-do-agente'
    | '/clientes/express-entulho/operacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  AulaZeroRoute: typeof AulaZeroRoute
  ComandosRoute: typeof ComandosRoute
  PortfolioRoute: typeof PortfolioRoute
  PromptPacksRoute: typeof PromptPacksRoute
  SeloDemoRoute: typeof SeloDemoRoute
  SelosRoute: typeof SelosRoute
  VeronicaAnalyticsRoute: typeof VeronicaAnalyticsRoute
  VeronicaCurriculoCertoRoute: typeof VeronicaCurriculoCertoRoute
  VeronicaCurriculoCertoRhRoute: typeof VeronicaCurriculoCertoRhRoute
  VeronicaNauticaRoute: typeof VeronicaNauticaRoute
  VeronicaRedeRoute: typeof VeronicaRedeRoute
  VeronicaSecurityRoute: typeof VeronicaSecurityRoute
  VideoIaRoute: typeof VideoIaRoute
  AdminArtigosRoute: typeof AdminArtigosRoute
  AdminImagensRoute: typeof AdminImagensRoute
  AdminVeronicaUniverseRoute: typeof AdminVeronicaUniverseRoute
  AdminWireRoute: typeof AdminWireRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogExpedienteRoute: typeof BlogExpedienteRoute
  BlogRedeDeFontesRoute: typeof BlogRedeDeFontesRouteWithChildren
  PreviewExpressOperationsBRoute: typeof PreviewExpressOperationsBRouteWithChildren
  PropostaExpressEntulhoRoute: typeof PropostaExpressEntulhoRoute
  SeloSerialRoute: typeof SeloSerialRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  BlogEditoriaBeatRoute: typeof BlogEditoriaBeatRoute
  ClientesExpressEntulhoOperacoesRoute: typeof ClientesExpressEntulhoOperacoesRouteWithChildren
  ClientesExpressEntulhoOperacoesDemoRoute: typeof ClientesExpressEntulhoOperacoesDemoRoute
  ClientesExpressEntulhoPropostaRoute: typeof ClientesExpressEntulhoPropostaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula-zero': {
      id: '/aula-zero'
      path: '/aula-zero'
      fullPath: '/aula-zero'
      preLoaderRoute: typeof AulaZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comandos': {
      id: '/comandos'
      path: '/comandos'
      fullPath: '/comandos'
      preLoaderRoute: typeof ComandosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-packs': {
      id: '/prompt-packs'
      path: '/prompt-packs'
      fullPath: '/prompt-packs'
      preLoaderRoute: typeof PromptPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selo-demo': {
      id: '/selo-demo'
      path: '/selo-demo'
      fullPath: '/selo-demo'
      preLoaderRoute: typeof SeloDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selos': {
      id: '/selos'
      path: '/selos'
      fullPath: '/selos'
      preLoaderRoute: typeof SelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veronica-analytics': {
      id: '/veronica-analytics'
      path: '/veronica-analytics'
      fullPath: '/veronica-analytics'
      preLoaderRoute: typeof VeronicaAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veronica-curriculo-certo': {
      id: '/veronica-curriculo-certo'
      path: '/veronica-curriculo-certo'
      fullPath: '/veronica-curriculo-certo'
      preLoaderRoute: typeof VeronicaCurriculoCertoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veronica-curriculo-certo-rh': {
      id: '/veronica-curriculo-certo-rh'
      path: '/veronica-curriculo-certo-rh'
      fullPath: '/veronica-curriculo-certo-rh'
      preLoaderRoute: typeof VeronicaCurriculoCertoRhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veronica-nautica': {
      id: '/veronica-nautica'
      path: '/veronica-nautica'
      fullPath: '/veronica-nautica'
      preLoaderRoute: typeof VeronicaNauticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veronica-rede': {
      id: '/veronica-rede'
      path: '/veronica-rede'
      fullPath: '/veronica-rede'
      preLoaderRoute: typeof VeronicaRedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veronica-security': {
      id: '/veronica-security'
      path: '/veronica-security'
      fullPath: '/veronica-security'
      preLoaderRoute: typeof VeronicaSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-ia': {
      id: '/video-ia'
      path: '/video-ia'
      fullPath: '/video-ia'
      preLoaderRoute: typeof VideoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/artigos': {
      id: '/admin/artigos'
      path: '/admin/artigos'
      fullPath: '/admin/artigos'
      preLoaderRoute: typeof AdminArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/imagens': {
      id: '/admin/imagens'
      path: '/admin/imagens'
      fullPath: '/admin/imagens'
      preLoaderRoute: typeof AdminImagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/veronica-universe': {
      id: '/admin/veronica-universe'
      path: '/admin/veronica-universe'
      fullPath: '/admin/veronica-universe'
      preLoaderRoute: typeof AdminVeronicaUniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wire': {
      id: '/admin/wire'
      path: '/admin/wire'
      fullPath: '/admin/wire'
      preLoaderRoute: typeof AdminWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/expediente': {
      id: '/blog/expediente'
      path: '/blog/expediente'
      fullPath: '/blog/expediente'
      preLoaderRoute: typeof BlogExpedienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rede-de-fontes': {
      id: '/blog/rede-de-fontes'
      path: '/blog/rede-de-fontes'
      fullPath: '/blog/rede-de-fontes'
      preLoaderRoute: typeof BlogRedeDeFontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/express-operations-b': {
      id: '/preview/express-operations-b'
      path: '/preview/express-operations-b'
      fullPath: '/preview/express-operations-b'
      preLoaderRoute: typeof PreviewExpressOperationsBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta/express-entulho': {
      id: '/proposta/express-entulho'
      path: '/proposta/express-entulho'
      fullPath: '/proposta/express-entulho'
      preLoaderRoute: typeof PropostaExpressEntulhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selo/$serial': {
      id: '/selo/$serial'
      path: '/selo/$serial'
      fullPath: '/selo/$serial'
      preLoaderRoute: typeof SeloSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/editoria/$beat': {
      id: '/blog/editoria/$beat'
      path: '/blog/editoria/$beat'
      fullPath: '/blog/editoria/$beat'
      preLoaderRoute: typeof BlogEditoriaBeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rede-de-fontes/relatorios': {
      id: '/blog/rede-de-fontes/relatorios'
      path: '/relatorios'
      fullPath: '/blog/rede-de-fontes/relatorios'
      preLoaderRoute: typeof BlogRedeDeFontesRelatoriosRouteImport
      parentRoute: typeof BlogRedeDeFontesRoute
    }
    '/clientes/express-entulho/operacoes': {
      id: '/clientes/express-entulho/operacoes'
      path: '/clientes/express-entulho/operacoes'
      fullPath: '/clientes/express-entulho/operacoes'
      preLoaderRoute: typeof ClientesExpressEntulhoOperacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/express-entulho/operacoes-demo': {
      id: '/clientes/express-entulho/operacoes-demo'
      path: '/clientes/express-entulho/operacoes-demo'
      fullPath: '/clientes/express-entulho/operacoes-demo'
      preLoaderRoute: typeof ClientesExpressEntulhoOperacoesDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/express-entulho/proposta': {
      id: '/clientes/express-entulho/proposta'
      path: '/clientes/express-entulho/proposta'
      fullPath: '/clientes/express-entulho/proposta'
      preLoaderRoute: typeof ClientesExpressEntulhoPropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/express-operations-b/$': {
      id: '/preview/express-operations-b/$'
      path: '/$'
      fullPath: '/preview/express-operations-b/$'
      preLoaderRoute: typeof PreviewExpressOperationsBSplatRouteImport
      parentRoute: typeof PreviewExpressOperationsBRoute
    }
    '/clientes/express-entulho/operacoes/': {
      id: '/clientes/express-entulho/operacoes/'
      path: '/'
      fullPath: '/clientes/express-entulho/operacoes/'
      preLoaderRoute: typeof ClientesExpressEntulhoOperacoesIndexRouteImport
      parentRoute: typeof ClientesExpressEntulhoOperacoesRoute
    }
    '/clientes/express-entulho/operacoes/$secao': {
      id: '/clientes/express-entulho/operacoes/$secao'
      path: '/$secao'
      fullPath: '/clientes/express-entulho/operacoes/$secao'
      preLoaderRoute: typeof ClientesExpressEntulhoOperacoesSecaoRouteImport
      parentRoute: typeof ClientesExpressEntulhoOperacoesRoute
    }
    '/clientes/express-entulho/operacoes/aprovacoes': {
      id: '/clientes/express-entulho/operacoes/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/clientes/express-entulho/operacoes/aprovacoes'
      preLoaderRoute: typeof ClientesExpressEntulhoOperacoesAprovacoesRouteImport
      parentRoute: typeof ClientesExpressEntulhoOperacoesRoute
    }
    '/clientes/express-entulho/operacoes/atendimento': {
      id: '/clientes/express-entulho/operacoes/atendimento'
      path: '/atendimento'
      fullPath: '/clientes/express-entulho/operacoes/atendimento'
      preLoaderRoute: typeof ClientesExpressEntulhoOperacoesAtendimentoRouteImport
      parentRoute: typeof ClientesExpressEntulhoOperacoesRoute
    }
    '/clientes/express-entulho/operacoes/cacambas': {
      id: '/clientes/express-entulho/operacoes/cacambas'
      path: '/cacambas'
      fullPath: '/clientes/express-entulho/operacoes/cacambas'
      preLoaderRoute: typeof ClientesExpressEntulhoOperacoesCacambasRouteImport
      parentRoute: typeof ClientesExpressEntulhoOperacoesRoute
    }
    '/clientes/express-entulho/operacoes/operacoes-hoje': {
      id: '/clientes/express-entulho/operacoes/operacoes-hoje'
      path: '/operacoes-hoje'
      fullPath: '/clientes/express-entulho/operacoes/operacoes-hoje'
      preLoaderRoute: typeof ClientesExpressEntulhoOperacoesOperacoesHojeRouteImport
      parentRoute: typeof ClientesExpressEntulhoOperacoesRoute
    }
    '/clientes/express-entulho/operacoes/regras-do-agente': {
      id: '/clientes/express-entulho/operacoes/regras-do-agente'
      path: '/regras-do-agente'
      fullPath: '/clientes/express-entulho/operacoes/regras-do-agente'
      preLoaderRoute: typeof ClientesExpressEntulhoOperacoesRegrasDoAgenteRouteImport
      parentRoute: typeof ClientesExpressEntulhoOperacoesRoute
    }
  }
}

interface BlogRedeDeFontesRouteChildren {
  BlogRedeDeFontesRelatoriosRoute: typeof BlogRedeDeFontesRelatoriosRoute
}

const BlogRedeDeFontesRouteChildren: BlogRedeDeFontesRouteChildren = {
  BlogRedeDeFontesRelatoriosRoute: BlogRedeDeFontesRelatoriosRoute,
}

const BlogRedeDeFontesRouteWithChildren =
  BlogRedeDeFontesRoute._addFileChildren(BlogRedeDeFontesRouteChildren)

interface PreviewExpressOperationsBRouteChildren {
  PreviewExpressOperationsBSplatRoute: typeof PreviewExpressOperationsBSplatRoute
}

const PreviewExpressOperationsBRouteChildren: PreviewExpressOperationsBRouteChildren =
  {
    PreviewExpressOperationsBSplatRoute: PreviewExpressOperationsBSplatRoute,
  }

const PreviewExpressOperationsBRouteWithChildren =
  PreviewExpressOperationsBRoute._addFileChildren(
    PreviewExpressOperationsBRouteChildren,
  )

interface ClientesExpressEntulhoOperacoesRouteChildren {
  ClientesExpressEntulhoOperacoesSecaoRoute: typeof ClientesExpressEntulhoOperacoesSecaoRoute
  ClientesExpressEntulhoOperacoesAprovacoesRoute: typeof ClientesExpressEntulhoOperacoesAprovacoesRoute
  ClientesExpressEntulhoOperacoesAtendimentoRoute: typeof ClientesExpressEntulhoOperacoesAtendimentoRoute
  ClientesExpressEntulhoOperacoesCacambasRoute: typeof ClientesExpressEntulhoOperacoesCacambasRoute
  ClientesExpressEntulhoOperacoesOperacoesHojeRoute: typeof ClientesExpressEntulhoOperacoesOperacoesHojeRoute
  ClientesExpressEntulhoOperacoesRegrasDoAgenteRoute: typeof ClientesExpressEntulhoOperacoesRegrasDoAgenteRoute
  ClientesExpressEntulhoOperacoesIndexRoute: typeof ClientesExpressEntulhoOperacoesIndexRoute
}

const ClientesExpressEntulhoOperacoesRouteChildren: ClientesExpressEntulhoOperacoesRouteChildren =
  {
    ClientesExpressEntulhoOperacoesSecaoRoute:
      ClientesExpressEntulhoOperacoesSecaoRoute,
    ClientesExpressEntulhoOperacoesAprovacoesRoute:
      ClientesExpressEntulhoOperacoesAprovacoesRoute,
    ClientesExpressEntulhoOperacoesAtendimentoRoute:
      ClientesExpressEntulhoOperacoesAtendimentoRoute,
    ClientesExpressEntulhoOperacoesCacambasRoute:
      ClientesExpressEntulhoOperacoesCacambasRoute,
    ClientesExpressEntulhoOperacoesOperacoesHojeRoute:
      ClientesExpressEntulhoOperacoesOperacoesHojeRoute,
    ClientesExpressEntulhoOperacoesRegrasDoAgenteRoute:
      ClientesExpressEntulhoOperacoesRegrasDoAgenteRoute,
    ClientesExpressEntulhoOperacoesIndexRoute:
      ClientesExpressEntulhoOperacoesIndexRoute,
  }

const ClientesExpressEntulhoOperacoesRouteWithChildren =
  ClientesExpressEntulhoOperacoesRoute._addFileChildren(
    ClientesExpressEntulhoOperacoesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  AulaZeroRoute: AulaZeroRoute,
  ComandosRoute: ComandosRoute,
  PortfolioRoute: PortfolioRoute,
  PromptPacksRoute: PromptPacksRoute,
  SeloDemoRoute: SeloDemoRoute,
  SelosRoute: SelosRoute,
  VeronicaAnalyticsRoute: VeronicaAnalyticsRoute,
  VeronicaCurriculoCertoRoute: VeronicaCurriculoCertoRoute,
  VeronicaCurriculoCertoRhRoute: VeronicaCurriculoCertoRhRoute,
  VeronicaNauticaRoute: VeronicaNauticaRoute,
  VeronicaRedeRoute: VeronicaRedeRoute,
  VeronicaSecurityRoute: VeronicaSecurityRoute,
  VideoIaRoute: VideoIaRoute,
  AdminArtigosRoute: AdminArtigosRoute,
  AdminImagensRoute: AdminImagensRoute,
  AdminVeronicaUniverseRoute: AdminVeronicaUniverseRoute,
  AdminWireRoute: AdminWireRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogExpedienteRoute: BlogExpedienteRoute,
  BlogRedeDeFontesRoute: BlogRedeDeFontesRouteWithChildren,
  PreviewExpressOperationsBRoute: PreviewExpressOperationsBRouteWithChildren,
  PropostaExpressEntulhoRoute: PropostaExpressEntulhoRoute,
  SeloSerialRoute: SeloSerialRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  BlogEditoriaBeatRoute: BlogEditoriaBeatRoute,
  ClientesExpressEntulhoOperacoesRoute:
    ClientesExpressEntulhoOperacoesRouteWithChildren,
  ClientesExpressEntulhoOperacoesDemoRoute:
    ClientesExpressEntulhoOperacoesDemoRoute,
  ClientesExpressEntulhoPropostaRoute: ClientesExpressEntulhoPropostaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
